
package swing;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Khairul Hakimi
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")//belows code is involving the management of the element use in the design interface (22-107)
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_DisplayAllMoneyRate = new javax.swing.JButton();
        jButton_AddCurrency = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_EditAboutUs = new javax.swing.JButton();
        jButton_RemoveMoneyRate = new javax.swing.JButton();
        jButton_SignOut = new javax.swing.JButton();
        jButton_UpdateMoneyRate1 = new javax.swing.JButton();
        jButton_Transaction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN HOME PAGE");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(184, 226, 138));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 450));

        jButton_DisplayAllMoneyRate.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_DisplayAllMoneyRate.setText("DISPLAY ALL CURRENCY");
        jButton_DisplayAllMoneyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DisplayAllMoneyRateActionPerformed(evt);
            }
        });

        jButton_AddCurrency.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_AddCurrency.setText("ADD CURRENCY");
        jButton_AddCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddCurrencyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 24)); // NOI18N
        jLabel1.setText("WELCOME TO THE ADMIN'S HOME");

        jButton_EditAboutUs.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_EditAboutUs.setText("EDIT ABOUT US");
        jButton_EditAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditAboutUsActionPerformed(evt);
            }
        });

        jButton_RemoveMoneyRate.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_RemoveMoneyRate.setText("REMOVE CURRENCY");
        jButton_RemoveMoneyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveMoneyRateActionPerformed(evt);
            }
        });

        jButton_SignOut.setBackground(new java.awt.Color(0, 0, 0));
        jButton_SignOut.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButton_SignOut.setForeground(new java.awt.Color(255, 255, 255));
        jButton_SignOut.setText("SIGN OUT");
        jButton_SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignOutActionPerformed(evt);
            }
        });

        jButton_UpdateMoneyRate1.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_UpdateMoneyRate1.setText("UPDATE CURRENCY");
        jButton_UpdateMoneyRate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateMoneyRate1ActionPerformed(evt);
            }
        });

        jButton_Transaction.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_Transaction.setText("DISPLAY ALL TRANSACTION");
        jButton_Transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_SignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_DisplayAllMoneyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_AddCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_UpdateMoneyRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_RemoveMoneyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_EditAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_DisplayAllMoneyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_AddCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_UpdateMoneyRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_RemoveMoneyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_EditAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_SignOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddCurrencyActionPerformed
        // to proceed to the Add Currency page
        AddCurrency ac = new AddCurrency();
        ac.setVisible(true);// to open the new page
        this.setVisible(false); // to close the existing page*/  
    }//GEN-LAST:event_jButton_AddCurrencyActionPerformed

    private void jButton_EditAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditAboutUsActionPerformed
        // to proceed to the Edit About Us order page
        try {
           UpdateAboutUs uau = new UpdateAboutUs();
           uau.setVisible(true);// to open the new page
        this.setVisible(false);// to close the existing page*/
        } catch (IOException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_EditAboutUsActionPerformed

    private void jButton_RemoveMoneyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveMoneyRateActionPerformed
            // to proceed to the Remove Money Rate user page
        try {
            RemoveMoneyRate rmr = new RemoveMoneyRate();
            rmr.setVisible(true);// to open the new page
            this.setVisible(false);// to close the existing page
        } catch (IOException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton_RemoveMoneyRateActionPerformed

    private void jButton_SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignOutActionPerformed
         // to proceed to the Admin login page
        LoginAccount la= new LoginAccount();
        la.setVisible(true);// to open the new page
        this.setVisible(false); // to close the existing page
    }//GEN-LAST:event_jButton_SignOutActionPerformed

    private void jButton_DisplayAllMoneyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DisplayAllMoneyRateActionPerformed
        // to proceed to the Display All Money Rate login page
        try {
            ViewCurrencyRate vcr = new ViewCurrencyRate();
            vcr.setVisible(true);// to open the new page
            this.setVisible(false); // to close the existing page*/
        } catch (IOException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_DisplayAllMoneyRateActionPerformed

    private void jButton_UpdateMoneyRate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateMoneyRate1ActionPerformed
        // TODO add your handling code here:
        
        try {
           UpdateCurrency uc = new UpdateCurrency();
           uc.setVisible(true);
        this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_UpdateMoneyRate1ActionPerformed

    private void jButton_TransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TransactionActionPerformed
        // TODO add your handling code here:
        try {
            ViewAllTransaction vat = new ViewAllTransaction();
            vat.setVisible(true);// to open the new page
            this.setVisible(false); // to close the existing page
        } catch (IOException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_TransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddCurrency;
    private javax.swing.JButton jButton_DisplayAllMoneyRate;
    private javax.swing.JButton jButton_EditAboutUs;
    private javax.swing.JButton jButton_RemoveMoneyRate;
    private javax.swing.JButton jButton_SignOut;
    private javax.swing.JButton jButton_Transaction;
    private javax.swing.JButton jButton_UpdateMoneyRate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
