
package swing;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.MyLogin;

/**
 *
 * @author Khairul Hakimi
 */
public class LoginAccount extends javax.swing.JFrame {
    public LoginAccount() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked") //belows code is involving the management of the element use in the design interface (10)
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_UsernameLabel = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel_passwordLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jButton_Register = new javax.swing.JButton();
        jLabel_ErrorLogin = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN ACCOUNT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(184, 226, 138));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 36)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel_UsernameLabel.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel_UsernameLabel.setText("USERNAME:");
        jLabel_UsernameLabel.setPreferredSize(new java.awt.Dimension(99, 25));

        jTextField_Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Username.setPreferredSize(new java.awt.Dimension(73, 26));
        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });

        jLabel_passwordLabel.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel_passwordLabel.setText("PASSWORD:");
        jLabel_passwordLabel.setPreferredSize(new java.awt.Dimension(100, 25));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(142, 26));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton_Login.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_Login.setText("LOGIN NOW");
        jButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseClicked(evt);
            }
        });
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jButton_Register.setBackground(new java.awt.Color(94, 197, 126));
        jButton_Register.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jButton_Register.setText("REGISTER HERE");
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel_ErrorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel_ErrorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        // to proceed to the register page
        Register rg = new Register();
	rg.setVisible(true);//to open the new page
	this.setVisible(false);// to close the existing page
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        //if the matric number is equal to admin and the password is 123456, it will bring the user to the admin mode page, or else it will bring the user to the normal user page
        if (jTextField_Username.getText().equals("admin") && jPasswordField1.getText().equals("admin123456")) {
            // to proceed to the admin home page
            AdminHomePage admin = new AdminHomePage();
            admin.setVisible(true);//to open the new page
            this.setVisible(false);// to close the existing page
        } 
        else {
            usernameFinal= jTextField_Username.getText();// get the username at the text field 
            passwordfinal=jPasswordField1.getText();// get the password at the text field 
            lgn.setUsername(usernameFinal);//get the access to the Mylogin's class to set the username
            lgn.setPassword(passwordfinal);//get the access to the Mylogin's class to set the Password
            try {
                if (verifyUser(lgn) == true){ //if the verifyUser is true (registered in the system) it will show successful message and directed the user to the home page or else it will display error message
                JOptionPane.showMessageDialog(this, "Successfully Logged In!"); //display successful message
                CustomerHomePage chp = new CustomerHomePage();
                chp.setVisible(true);//to open the new page
                this.setVisible(false);// to close the existing page
                }
                else{
                    JOptionPane.showMessageDialog(this, "Access Denied!! Please Try Again!");//display error message
                }
            } 
            catch (IOException ex) {
                Logger.getLogger(LoginAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseClicked
        // element use in the GUI's design
    }//GEN-LAST:event_jButton_LoginMouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // element use in the GUI's design
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // element use in the GUI's design
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    String usernameFinal; //declare username
    String passwordfinal;   //declare password
    MyLogin lgn= new MyLogin(); //it will refer the MyLogin's class 
    
    public boolean verifyUser(MyLogin lgn)throws IOException{//to verify user either has been register or not
	try{
            File logins = new File("UserLogin.txt");// it will open  the UserLogin.txt file
            if(!logins.exists()){//if the file does not exist in the folder it will create a new file named UserLogin.txt
                logins.createNewFile();
            }
            BufferedWriter bw = new BufferedWriter(new FileWriter(logins));//it will write text  to character output stream
            PrintWriter pw = new PrintWriter(bw); //format the content to be appended in the file
            FileReader fr=new FileReader("UserData.txt");// it will open the UserData.txt file
            try (BufferedReader br = new BufferedReader(fr)) {//to read the file's content that has been declare 
                String line=null;//declare the line
                String []splt=null;//declare the splt
                
                while((line=br.readLine())!=null){
                    splt=line.split(",:");//Split the data by including ,:
                    lgn.setUserId(Integer.parseInt(splt[0])); //set the customer id by refering to the Mylogin's class and return as integer
                    
                    //if the content in the file is the same with the input gain from the text field then it will be true
                    if(splt[2].equals(lgn.getUsername()) && splt[3].equals(lgn.getPassword())) {
                        System.out.println(lgn.getUserId());
                        pw.println(lgn.getUserId()+",:"+lgn.getUsername());
                        pw.flush();//flushes the characters from the stream and then closes it
                        pw.close();// to close the open UserData.txt file
                        return true;
                    }
                }
            }
        }
        catch(IOException e){
            System.out.println("FileNotFound");
        }
    return false;
}

	/**
	 * @param args the command line arguments
	 */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new LoginAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ErrorLogin;
    private javax.swing.JLabel jLabel_UsernameLabel;
    private javax.swing.JLabel jLabel_passwordLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}

